docs: update design
IBM/ibm-storage-odf-operator pull request #23
Opened 2021-07-22 05:30 UTC by gyaozhou

Remove n/a parts. Add corresponding links to exporter and CSI driver.

2021-07-22 05:42 UTC, iamniting requested changes

2021-07-22 05:42 UTC, iamniting commented on docs/design.md
>  1. This operator only support one instance only. So, ODF should prevent client from creating more if there is already a storage cluster created.
```suggestion
1. This operator only support one instance only. So, ODF should prevent client from creating more if there is already a flash cluster created.
```

2021-07-23 09:23 UTC, iamniting approved these changes

2021-07-26 09:37 UTC, lbscorpio approved these changes
/lgtm

2021-07-26 09:39 UTC, merged